name: device_info
description: "A Flutter plugin to retrieve detailed device connectivity and capability information."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.device_info
        pluginClass: DeviceInfoPlugin
      ios:
        pluginClass: DeviceInfoPlugin
